### ISSUE TITLE
Create a TexBox for PATH

### ISSUE THREAD

**Issue by ulises2k** [arnobpl/SymlinkCreator#10]
It should have a textbox where you can enter the path of a directory, because if the directory is hidden, such as "c:\Users\ulise\AppData\Roaming\" it does not appear.

![image](https://github.com/arnobpl/SymlinkCreator/assets/2415609/c8869388-3c1d-454f-8a70-9c5afbfcd25e)

**Comment by arnobpl** [comment]
Thank you for your constructive feedback. It really helps to improve SymlinkCreator.

I have a plan to implement this one. I have quickly checked for an implementation. This one might be used: https://github.com/DinoChiesa/DotNetZip/blob/master/Zip/Resources/FolderBrowserDialogEx.cs

I will check for other options before implementation.

**Comment by arnobpl** [comment]
Also, one correction on your post. Hidden folders are actually shown on the folder browser dialog if your File Explorer has the hidden items setting enabled. But I agree, having a textbox for the folder browser dialog would be great.

Happy symlinking! :)
