### ISSUE TITLE
Error for incorrect file system type

### ISSUE THREAD

**Issue by SolarSciencePup** [arnobpl/SymlinkCreator#11]
Idea?
⌈¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯⌉
|                                        |
|❌ Incorrect file system  |
|                                 Ok   |
⌊__________________________ ⌋

**Comment by SolarSciencePup** [comment]
Broke :(

**Comment by arnobpl** [comment]
What is your file system for destination path's partition drive? It must be NTFS.

**Comment by SolarSciencePup** [comment]
I already knew about that it is just the software didn't spit an error so I had to research about it

**Comment by arnobpl** [comment]
Hope that you have figured out the issue. If you are using NTFS but still get the error, let me know.

Happy symlinking! :)

**Comment by SolarSciencePup** [comment]
No I never got an error and I was suggesting you add it

**Comment by arnobpl** [comment]
I see. Sorry, misunderstood your issue.

**Comment by arnobpl** [comment]
It is a good idea. Thank you for your feedback. I think, mklink command will fail in that case. So, an easy way to implement this is to check for error code of mklink command.
