### ISSUE TITLE
Add Symlink Trail

### ISSUE THREAD

**Issue by Sniper199999** [arnobpl/SymlinkCreator#12]
(Feature Request) Add a text file in a folder in the Source Directory which contains the Destination Directory path. 

The Folder structure can be such:
Folder "Symlink Trail" > filename.txt > "destination_path(s)/filename" 

Each filename will have different text file, so we can see where all the symlinks for this specific file were created
This will be useful to keep track of symlinks and delete them when we delete the original files...

Further up, we can also have a function to auto delete symlinks if the file is not present/deleted in source directory.

**Comment by arnobpl** [comment]
Thank you for using Symlink Creator and the feature request.

While I am not sure about the new feature's timeline, the feature can be implemented externally using a simple script like Python, or even Powershell script. Here is how:
1. First, before symlink creation using Symlink Creator, check the box "Retain script file after execution".
2. After clicking "Create symlinks" button, symlinks will be created and the script file (say `SymlinkCreator_123456789.bat`) will be preserved in the app directory.
3. Write a Python/Powershell script (or any other language) to parse `SymlinkCreator_123456789.bat` file to get the source file/folder paths and their symlink paths.
4. Create text files in source file/folder paths and append the symlink path in the text files.
5. That is it!

Happy Symlinking!
