### ISSUE TITLE
Why does this version add so many DLLs?

### ISSUE THREAD

**Issue by fxzxmicah** [arnobpl/SymlinkCreator#14]
![image](https://github.com/arnobpl/SymlinkCreator/assets/48860358/1fe164d6-9ab6-4fba-81ba-bbf2761f8a12)
Is it really necessary to have DLLs like these?

**Comment by arnobpl** [comment]
Thank you for raising your concern about having multiple DLL files in release v1.2.3. I will try to release a single-file app as it was before. The reason for having multiple DLL files in v1.2.3 is some framework upgrade for the folder browser. If you delete all the non-EXE files, the folder browser may not work and crash SymlinkCreator. But I have a fast follow-up plan to make it even better. Stay tuned!

Happy symlinking! :)
