### ISSUE TITLE
Question: Retain script file - but where is it?

### ISSUE THREAD

**Issue by Torqueitup** [arnobpl/SymlinkCreator#17]
First, its a great little app.
There is a check box to enable retaining the script file after execution.  If selected, where does the script file get stored?

**Comment by arnobpl** [comment]
Hello, the script file is stored in the same directory as the Symlink Creator EXE file. But since you are asking, I plan to add something to the UI such as a tooltip to communicate it better with users.

Happy Symlinking!

**Comment by Torqueitup** [comment]
Excellent, and thanks

**Comment by Torqueitup** [comment]
After investigating further, I found the scripts which had been generated by Symlink.  They were on the desktop, not in the same directory as the Symlink Creator EXE file.  I've probably got too many shortcuts on my desktop which is why I didn't pick them out straight away.

**Comment by arnobpl** [comment]
Thank you for confirming the script file location! I have one question related to your case. Could you tell me the "Start in" field of the shortcut of Symlink Creator? I want to know if the "Start in" field is the desktop path or the application path.

**Comment by Torqueitup** [comment]
Aha, that explains it.
The .exe file has been extracted to the desktop with no shortcut being required, thus the script files will end up on the desktop.  
I can manually create a directory in the \programs folder then create a shortcut to it on the desktop which will then be similar to what you have shown above.
