### ISSUE TITLE
how to delete already created symlinks?

### ISSUE THREAD

**Issue by naseerpvp** [arnobpl/SymlinkCreator#18]
so i have linked a dll file to a game install folder in a subfolder called mods
and when ever i delete the .symlink file 
the game exe crashes and says it's missing said file

i don't want the symlink anymore how do i go about deleting that

sorry i am newbie

**Comment by arnobpl** [comment]
If you want to delete symlinks, you can delete them as regular files. For example, you can right-click the symlink file and click Delete icon/text. Let me know if the issue is still not resolved.

Happy symlinking! :)
