### ISSUE TITLE
backup

### ISSUE THREAD

**Issue by coccobellof5** [arnobpl/SymlinkCreator#20]
Hi, thank you for this application.
But I was curious, is there a way to back up?

I created a list of over 200 files, renamed them by hand and corrected them.
Each symlink file points to an external disk.

I tried compressing the list into a .tar file (I'm aware that it saves the symlinks), but when I extract to another computer, it changes all my destinations to C:\

Is there a solution?
Is there a solution to copy the symlink list with its subfolders to other computers?

I hope you have a solution.
Thank you

**Comment by arnobpl** [comment]
Hi, thank you for using Symlink Creator!

From what I understand your use case is: you have an external drive shared by two computers. And, you want some of the files/folders to be copied from one computer to another computer through the external drive as an intermediate medium. Is it correct?

If that is it, I don't think compressing the symlinks and sharing with the other computer is right approach. Instead, you can use a backup tool in which you can make a list of the files to be copied from the external drive. You can use a free tool such as FreeFileSync. It also supports symlink copying (either copying symlink as symlink or copying symlink as actual file, [more info](https://freefilesync.org/manual.php?topic=comparison-settings)).

Hope that helps.

Happy symlinking! :)
