### ISSUE TITLE
Can this be made to work in reverse?

### ISSUE THREAD

**Issue by brybrant** [arnobpl/SymlinkCreator#3]
Hi. Nice work. Could you please make this software work in reverse to the way it currently does?
Currently the "destination path" is where the symbolic link is placed, but I want all of the "source files" to be replaced by symbolic links that point to a single 'master file' that is moved to the destination path.

I have a folder structure like this:
```
|- folder1/duplicateFile.png
|- folder2/duplicateFile.png
```

But I would like to create a structure like this:
```
|- folder1/linkToOriginal.symlink
|- folder2/linkToOriginal.symlink
|- folder3/original.png
```

This way I can have a single 'master file' and the rest can be symbolic links so I can save space!

**Comment by arnobpl** [comment]
Thank you for using the software and suggesting the feature! I will probably try to add the feature but not sure when I can do that.
