### ISSUE TITLE
[REQ] Add the option to make hard links instead of symbolic

### ISSUE THREAD

**Issue by vangeliis** [arnobpl/SymlinkCreator#4]
Hey,

Great piece of software, thanks.
Please would you consider adding an option to create hard links (mklink /h), perhaps by adding a tick box above/below the "retain script file after execution" and once ticked change the 'Create symlinks' button to 'Create hard links'?

See what you think.
Many thanks.

**Comment by arnobpl** [comment]
Thank you for suggesting the feature! I will try to add the feature but not sure when I can do that.
