### ISSUE TITLE
When adding a second folder, the path of previous selection should be pre-selected

### ISSUE THREAD

**Issue by CFR0901** [arnobpl/SymlinkCreator#5]
I have multiple folders in one path that I want to create a link for. Each time I need to navigate down the whole path. It would be nice to have the previous path pre-selected when the next folder is selected.

Otherwise, it would be helpful to set the path manually via copy&paste.

**Comment by arnobpl** [comment]
Thank you for using Symlink Creator and your suggestion to improve it further.

**Comment by arnobpl** [comment]
For a quick solution, you can drag-n-drop from File Explorer instead of clicking the "Add folder" button to select the folders for symlinks.

**Comment by arnobpl** [comment]
Please check the new release to have the enhancement you suggested. Thank you again for being part of improving Symlink Creator!
